// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "syncNoteIds": string;
      "syncPeriodSeconds": number;
      "syncAttachmentFolder": string;
      "autoAnnotation": boolean;
      "insertLinkPosition": string;
      "workspace.outline.expandLevel": number;
      "workspace.outline.keepLinks": boolean;
      "editor.noteLinkPreviewType": string;
      "editor.useMagicKey": boolean;
      "editor.useMarkdownPaste": boolean;
      "openNote.takeover": boolean;
      "openNote.defaultAsWindow": boolean;
      "exportNotes.takeover": boolean;
      "annotationNote.enableTagSync": boolean;
    };
  }
}
